name: Deploy on push

on:
    push:
        branches: [ staging ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Configure SSH
              run: |
                mkdir -p ~/.ssh/
                echo "$SSH_PRIVATE_KEY" > ~/.ssh/staging.key
                chmod 600 ~/.ssh/staging.key
                cat >>~/.ssh/config <<END
                Host staging
                    HostName $SSH_HOST
                    User $SSH_USER
                    Port $SSH_PORT
                    IdentityFile ~/.ssh/staging.key
                    StrictHostKeyChecking no
                END
              env:
                SSH_USER: ${{ secrets.SSH_USER }}
                SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                SSH_HOST: ${{ secrets.SSH_HOST }}
            - name: Pull
              run: ssh staging "./build.sh"
